services:
  traefik:
    image: traefik:v3.5
    command:
      # Enabling Docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      #- "--providers.docker.exposedbydefault=false"
      # Entry points
      - "--entrypoints.satisfactory-7777-tcp.address=:7777/tcp"
      - "--entrypoints.satisfactory-7777-udp.address=:7777/udp"
      - "--entrypoints.satisfactory-8888-tcp.address=:8888/tcp"
    ports:
      - "80:80"
      - "8080:8080"
      - "7777:7777"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock