services:
  traefik:
    image: traefik:v3.5
    command:
      # Enabling Docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      #- "--providers.docker.exposedbydefault=false"
      # Entry points
      - "--entrypoints.satisfactory-17777-tcp.address=:17777/tcp"
      - "--entrypoints.satisfactory-17777-udp.address=:17777/udp"
      - "--entrypoints.satisfactory-18888-tcp.address=:18888/tcp"
    ports:
      - "1080:80"
      - "18080:8080"
      - "17777:17777"
      - "18888:18888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock