services:
  traefik:
    image: traefik:v3.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "1080:80"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock