services:
  nitrox:
    image: "cuteminded/nitrox-server:latest"
    restart: "unless-stopped"
    tty: true
    stdin_open: true
    ports:
      - "11000:11000/udp" # Nitrox Game Port
      - "50000:50000" # GUI Config Editor Port (if enabled)
    environment:
      TZ: "Etc/GMT-5"
      SUBNAUTICA_INSTALLATION_PATH: "/mnt/subnautica"
    volumes:
      - subnautica-phil-config-01:/app/config/Nitrox
      - subnautica-phil-gamefiles-01:/mnt/subnautica

volumes:
  subnautica-phil-gamefiles-01:
    name: subnautica-phil-gamefiles-01
  subnautica-phil-config-01:
    name: subnautica-phil-config-01
