services:
  app:
    image: advplyr/audiobookshelf:edge
    restart: unless-stopped
    ports:
      - '13787:80' # Public HTTP Port

    volumes:
      - DS920-media:/audiobooks
      - DS920-media:/podcasts
      - audiobooks-config:/config
      - audiobooks-metadata:/metadata

volumes:
  audiobooks-config:
  audiobooks-metadata:
  DS920-media:
    external: true